[[redirects]]
  from = "/book-flights/en/*"
  to = "https://vk-prod.airtrfx.com/book-flights/en/:splat"
  status = 200
  force = true

[[redirects]]
 from = "/em-assets/*"
  to = "https://vk-prod.airtrfx.com/em-assets/:splat"
  status = 200
  force = true
